# Generated by Django 5.0.6 on 2024-05-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageMetadata",
            fields=[
                ("user_id", models.UUIDField(primary_key=True, serialize=False)),
                ("skin_tone", models.CharField(default="TBD", max_length=10)),
                ("malignant", models.CharField(default="TBD", max_length=10)),
                ("image", models.ImageField(upload_to="raw_data/nonlabelled_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rogeliotable",
            },
        ),
    ]
