# Generated by Django 5.0.6 on 2024-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dermachat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemetadata",
            name="malignant",
            field=models.BooleanField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="imagemetadata",
            name="skin_tone",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
