# Generated by Django 5.0.6 on 2024-05-14 13:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dermachat", "0003_alter_imagemetadata_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemetadata",
            name="user_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
