# Generated by Django 5.0.6 on 2024-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dermachat", "0005_alter_imagemetadata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemetadata",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="raw_data/unlabelled_images/"
            ),
        ),
    ]
