# Generated by Django 5.0.6 on 2024-05-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoctorSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("skin_tone", models.CharField(max_length=100)),
                ("melanoma", models.BooleanField(default=False)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
