# Generated by Django 5.0.6 on 2024-05-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dermachat", "0006_alter_imagemetadata_image"),
        ("doctor_interface", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_tone",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ]
                    ),
                ),
                ("malignant", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dermachat.imagemetadata",
                    ),
                ),
            ],
            options={
                "db_table": "doctor_classification",
            },
        ),
        migrations.DeleteModel(
            name="DoctorSelection",
        ),
    ]
