# Generated by Django 5.0.6 on 2024-05-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dermachat", "0006_alter_imagemetadata_image"),
        ("doctor_interface", "0004_alter_doctorclassification_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorclassification",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dermachat.imagemetadata",
            ),
        ),
    ]
