# Generated by Django 5.0.6 on 2024-05-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_interface", "0005_alter_doctorclassification_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorclassification",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="prepared/classified_images/images_of_users"
            ),
        ),
    ]
