# Generated by Django 5.0.6 on 2024-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_interface", "0006_alter_doctorclassification_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorclassification",
            name="id",
        ),
        migrations.AlterField(
            model_name="doctorclassification",
            name="user_id",
            field=models.UUIDField(
                default=None, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
