"""
Django settings for pipino_doctorino project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
# import os
# import boto3
# from storages.backends.s3boto3 import S3Boto3Storage

# class Credentials():
#     AWS_ACCESS_KEY_ID = 'ASIAXB7FCAWSJRR37IVG'
#     AWS_SECRET_ACCESS_KEY = '2gkKoyJVOUqCF0yIhyPeG6OmX34gt9ISTVQeYXEl'
#     AWS_SECRET_TOKEN = 'IQoJb3JpZ2luX2VjEAEaCXVzLXdlc3QtMiJHMEUCIDNWYA8HURQmlfft4cfJ4KDAOt3RH7WWtoOVrFyNWDvBAiEA714QfCmxQ+HqmiUos8/uQlJxO2YgT6AtMe5GIpfqY3cqqQIIShAAGgw0ODUyNzQ4MTM4NjAiDL+aa79r40slN0MigiqGAg9Iiapte0P/khXKWoNE374Bq3Co/Az5OPhISC1gZoYJMyewDa7JsL0ZfISLDyAzWG4on0jRHV5heTROSkxG0KBmXeWsqfZGJ1gOY2f22ZNaDIVzy6T5D5Ra8gmDVD/IGGVxa7Bm65L+j2vBLL/29CJziHDsRCFFbiHzxirDAr5oLUYv1JhrFZ74qlbiMK4ZL9td/qZi7QfkiU1Mw/eIAE7JNosFel8ppF4CA2rynAqf0JfvkIUr8Jd+X0iRJnkKHrIt9lD2qMRfdAd+LECOx9MAliquEkm+oX94WKoSruw1xTPQU76LERvZbXaUZT3KQklijCesIvTVvvKKW7SIf9Ujul5ySwYwoIqVsQY6nQFbCy14Q2FAPXU98hJEQo1IsSTSkNlXvX9dp0D4kUG1h54JNyQxB4poUwS4fE3F6G05M5ckp6FAkRX3kc5WCATe+IbwgUAhNOkWrwy/T9sYddT7O+uemLVDj6nmZDED8gaXmgsuSJdUpDP7LSJU4HsghjZRFeQP+17cDvRaQVQkdbN1YZf812XpHN0MHcZlJY/5vAnCUfrLHFExOSmG'
#     AWS_STORAGE_BUCKET_NAME = 'provafinalproject'
#     AWS_STORAGE_PATH = 'models/cnn/skin_cancer_model.pkl'
#     AWS_PICKLE_MODEL = 'skin_cancer_model.pkl'

# # Configure static and media file storage
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATIC_URL = f'https://provafinalproject.s3.amazonaws.com/static/'
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(t((hg7l&m=&y$*6f*6k@7lw$patq^!3lz7cq-%g$@v9j!bb1^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dermachat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pipino_doctorino.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pipino_doctorino.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
